# Site settings
title: Aatif Jiwani's website
email: aatif.jiwani@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aatif Jiwani's personal website

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
